### ISSUE TITLE
Issues with Simulation and running the model

### ISSUE THREAD

**Issue by PhindyChimele20** [kr-colab/mapNN#4]
Hi, I read your paper and it is pretty cool. I am interested in trying the analysis in our SNPs dataset, so I have been following the instructions on the documentation and tried to run the analysis on the wolves example dataset that is provided before I can run it on my own data. However, I have been encountering problems 1)When I run the simulation with the benchmark.slim file I am getting an error: "Finished generation" "99" "; N=" "10006"
"Finished generation" "100" "; N=" "9951"
ERROR (EidosSymbolTable::_GetValue): undefined identifier De.

Error on script line 120, character 22:

            De[i,j] = De[i,j] + 1;

2) When I tried to run the Empirical analysis using the examples dataset provided, running the simulation with the wolves.slim file gives; slim -d "MAP_FILE_0='Examples/Empirical/cookie_123_disp.csv'" -d "MAP_FILE_1='Examples/Empirical/cookie_123_dens.csv'" -d "OUTNAME='Examples/Empirical/sim'" -d SEED=2 SLiM_recipes/wolves.slim
// Initial random seed:
6770018400048796296

// RunInitializeCallbacks():
initializeSLiMModelType(modelType = 'nonWF');
initializeSLiMOptions(dimensionality = 'xy');
initializeTreeSeq(checkCoalescence = T);
#WARNING (Eidos_ExecuteFunction_readCSV): function readCSV() could not read file at path /home/chriscs/Software/disperseNN3/Wolves/genetic_map.txt.
ERROR (EidosInterpreter::Evaluate_Call): operand type NULL is not supported by the '.' operator.

Error on script line 25, character 14:

    ends = map.getValue("ends");
I am not sure if there's an issue with the file?

3) So does running the mapnn --processing step, it seems to be giving an issue: I ran the script provided as the example python mapnn.py --preprocess --out Examples/Empirical/ --simid 1 --seed 1 --num_snps 10627 --n 94 --tree_list /home/pntuli/lustre/mapNN/tempout/tree_list.txt --target_list /home/pntuli/lustre/mapNN/tempout/map_list.txt --map_width 50 --slim_width 7109.537608030495 --habitat_map Examples/Empirical/wolf_distribution.png --empirical Examples/Empirical/wolves_n94 --chroms 38
2024-10-10 15:31:06.155360: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-10 15:31:06.227482: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-10 15:31:06.228105: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-10 15:31:07.464549: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
starting pre-processing pipeline
getting mean from training, on sim 0
getting sd from training, on sim 0
Traceback (most recent call last):
  File "/mnt/lustre/users/pntuli/mapNN/mapnn.py", line 1250, in <module>
    preprocess()
  File "/mnt/lustre/users/pntuli/mapNN/mapnn.py", line 958, in preprocess
    geno_mat, locs = training_generator.sample_ts(trees[args.simid-1], args.seed) # -1 for 0-indexing
  File "/mnt/lustre/users/pntuli/mapNN/data_generation.py", line 209, in sample_ts
    tss.append(tskit.load(fp))
  File "/apps/chpc/bio/anaconda3-2020.02/envs/mapnn/lib/python3.9/site-packages/tskit/trees.py", line 3289, in load
    return TreeSequence.load(
  File "/apps/chpc/bio/anaconda3-2020.02/envs/mapnn/lib/python3.9/site-packages/tskit/trees.py", line 4084, in load
    file, local_file = util.convert_file_like_to_open_file(file_or_path, "rb")
  File "/apps/chpc/bio/anaconda3-2020.02/envs/mapnn/lib/python3.9/site-packages/tskit/util.py", line 692, in convert_file_like_to_open_file
    _file = open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'tempout/recap_123_chr1.trees'

Please assist, as I am interested in trying this analysis on my SNPs dataset.

**Comment by andrewkern** [comment]
thanks for your interest in the software. you have a bunch of questions here so let's just start with the first one, which seems to be some difficulty in running the `benchmark.slim` SLiM recipe. What version of SLiM are you running?

**Comment by PhindyChimele20** [comment]
I am running SLiM version 4.0.1

**Comment by andrewkern** [comment]
I was able to run the `benchmark.slim` recipe with SLiM version 4.0.1-- can you post the complete command line you are using?
