### ISSUE TITLE
Error "sorry, Dude. Didn't generate enough snps."

### ISSUE THREAD

**Issue by ruizeliot** [kr-colab/mapNN#5]
Hi! Thank you for this new program! Could you explain me why I get the error "sorry, Dude. Didn't generate enough snps." during preprocessing? 

The error occurs using the function `sample_ts` with the following code: `geno_mat, locs = training_generator.sample_ts(trees[i], args.seed)`. The function runs for about 1h and then generates this error message. Here is the command line I am using below: 
`python mapnn.py --preprocess  --gpu_index any --seed 123 --num_snps 100 --n 49 --map_width 649 --slim_width 649 --sample_grid 1 --tree_list ../ADLIFISH_eruiz/test1_mapNN_chr_t_top_100_snp/preprocessing_mapNN/sim_mapNN/chr_t_top_100_sim_123_tree_list.txt --target_list ../ADLIFISH_eruiz/test1_mapNN_chr_t_top_100_snp/preprocessing_mapNN/cookie_mapNN/chr_t_top_100_cookie_list.txt --habitat_map ../ADLIFISH_eruiz/test1_mapNN_chr_t_top_100_snp/data_mapNN/depth_map_wio_rgb_cropped.png --empirical ../ADLIFISH_eruiz/test1_mapNN_chr_t_top_100_snp/data_mapNN/Chr_t_unlinked_snp_subset_top_100_loci_dapc_fixed_mapnn --out ../ADLIFISH_eruiz/test1_mapNN_chr_t_top_100_snp/preprocessing_mapNN/preprocess_mapNN`

The trees were generated with 2 SliM iterations (for the test as I have a big region):
`defineConstant("W", 649);
 defineConstant("L", 4);
 defineConstant("G", 1e8);
 defineConstant("FECUN", 1/L);
 defineConstant("maxgens", 2);`

Thank you in advance, ER

**Comment by chriscrsmith** [comment]
Hi and thank you for posting the issue! Is this using one of the slim recipes from the mapnn repo? Did you run slim without mutations, recapitate with msprime, and add mutations to the tree sequence?

**Comment by ruizeliot** [comment]
Thank you for your quick answer. I used the benchmark.slim that I just slightly modified to changed the image width and the number of generations.

`initialize() {
    if (!exists("SEED")) defineConstant("SEED", 123);
    setSeed(SEED);
    initializeSLiMModelType("nonWF");
    initializeSLiMOptions(dimensionality="xy");
    initializeTreeSeq(checkCoalescence=T);

    map_file = readCSV(MAP_FILE_0, colNames=F);
    map_file = map_file.asMatrix();
    map_file = sqrt(map_file^2 + 0.5*(1^2)); // convert sigma to sigma_f
    defineConstant("SD_vals", map_file);
    map_file = readCSV(MAP_FILE_1, colNames=F);
    map_file = map_file.asMatrix();
    defineConstant("K_vals", map_file);

    defineConstant("W", 649);  // TO MODIFY: Image width (= height)
    defineConstant("L", 4);    // TO MODIFY: Mean lifetime at stationarity
    defineConstant("G", 1e8);  // TO MODIFY: Genome length
    defineConstant("FECUN", 1/L); // TO MODIFY: Mean fecundity
    defineConstant("maxgens", 2); // TO MODIFY: Number of iterations

    if (!exists("maxgens")) defineConstant("maxgens", 1000);
    if (!exists("gens_b4_record")) defineConstant("gens_b4_record", 100);     	
    if (!exists("OUTNAME")) defineConstant("OUTNAME", ""); 	
    if (!exists("W")) defineConstant("W", 50);  // width and height of the simulated area
    if (!exists("SM")) defineConstant("SM", 1);
    if (!exists("SI")) defineConstant("SI", 1);

    initializeMutationType("m1", 0.5, "g", 0.0, 2);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, G-1);
    initializeMutationRate(0);
    initializeRecombinationRate(1e-8);  

    // spatial competition
    initializeInteractionType(1, "xy", reciprocal=T, maxDistance=SI * 3);
    i1.setInteractionFunction("n", 1.0/(2*PI*SI^2), SI);
    
    // mate choice
    initializeInteractionType(2, "xy", reciprocal=T, maxDistance=SM * 3);
    i2.setInteractionFunction("n", 1.0/(2*PI*SM^2), SM);
    
    // initialize vars for tracking density
    if (!exists("GRID_COARSENESS")) defineConstant("GRID_COARSENESS", W);
    defineConstant("De", matrix(rep(0, GRID_COARSENESS*GRID_COARSENESS), GRID_COARSENESS, GRID_COARSENESS));
    defineConstant("sigmas", matrix(rep(0.0, GRID_COARSENESS*GRID_COARSENESS), GRID_COARSENESS, GRID_COARSENESS));
    defineConstant("offspring_counts", matrix(rep(0, GRID_COARSENESS*GRID_COARSENESS), GRID_COARSENESS, GRID_COARSENESS));
}


reproduction() {
        mate = i2.drawByStrength(individual, 1);
    	location = individual.spatialPosition; 
    	SD = p1.spatialMapValue("sigma", location); 
	 
    	if (mate.size()) {
            nOff = rpois(1, FECUN);
            for (i in seqLen(nOff)) {                    		
                pos = location + rnorm(2, 0, SD);
                if (p1.pointInBounds(pos)){
                    //if (p1.spatialMapValue("K", pos) > 1e-10) { // absorbing boundary for wolf habitat
                        offspring = subpop.addCrossed(individual, mate);
                        offspring.setSpatialPosition(pos);

                        // tracking offpring
                        individual.tag = individual.tag + 1; // adding new offspring for the mother
                        mate.tag = mate.tag + 1; // adding offspring for the father
                        offspring.tag = 0; // initialize tag for offspring
                        x0 = pos[0];
                        y0 = pos[1];
                        x1 = individual.spatialPosition[0];
                        y1 = individual.spatialPosition[1];
                        x2 = mate.spatialPosition[0];
                        y2 = mate.spatialPosition[1];
                        mom_dist_x = (x0-x1)^2; // squared distance along an axis
                        mom_dist_y = (y0-y1)^2;
                        dad_dist_x = (x0-x2)^2;
                        dad_dist_y = (y0-y2)^2;
                        mean_dist = (mom_dist_x + dad_dist_x + mom_dist_y + dad_dist_y)/4; // mean squared distance to parents
                        offspring.tagF = mean_dist;
                    //}
                }
            }
        }
    return;
}

1 early() {
    sim.addSubpop("p1", asInteger(mean(K_vals) * W * W)); // initialize with mean K
    p1.individuals.tag = 0; // "tag" property (int) counts the number of offspring
    p1.individuals.tagF = 0.0; // "tagF" (float) tracks mean distance to parents
    p1.setSpatialBounds(c(0, 0, W,W));  
    print(c("sigma range",range(SD_vals)));
    print(c("K range",range(K_vals)));
    p1.defineSpatialMap("sigma", "xy", SD_vals, interpolate=T);
    p1.defineSpatialMap("K", "xy", K_vals, interpolate=T);


    for (ind in p1.individuals) {
        K = 0; 
        while (K < 1e-10) { // important for wolf habitat map
            proposed = p1.pointUniform();	
            K = p1.spatialMapValue("K", proposed);       
                        }
        ind.setSpatialPosition(proposed);
    }
    i1.evaluate(sim.subpopulations);
}

early() {
    i1.evaluate(p1);
    inds = p1.individuals;
    competition = i1.localPopulationDensity(inds); // new
    locations = inds.spatialPosition; //[ rep(c(T,T), inds.size()) ];
    K = p1.spatialMapValue("K", locations);
    RHO = FECUN/((1+FECUN) * K); // constant in spatial competition function
    inds.fitnessScaling = 1/(1 + RHO * competition);

    // track density
    locs = asInteger(floor((inds.spatialPosition/W) * GRID_COARSENESS));  // finds pixel for each individual location
    if (sim.cycle > gens_b4_record) {	
        for (ind in seqLen(length(inds))) {
	    i = locs[ind*2];
	    j = locs[ind*2+1];
	    j = GRID_COARSENESS-j-1;  // flip to convert between slim and np.array. -1 for zero indexing
	    De[i,j] = De[i,j] + 1;
        }
    }
}

// death
survival() {
    if (!surviving) { // record data for dead individuals      
        if (sim.cycle > gens_b4_record) {
	    weighted_dist = individual.tagF*individual.tag;
    	    loc = asInteger(floor((individual.spatialPosition/W) * GRID_COARSENESS));
            i = loc[0];
            j = loc[1];
            j = GRID_COARSENESS-j-1;  // flip to convert between slim and np.array. -1 for zero indexing
            sigmas[i,j] = sigmas[i,j] + weighted_dist;  // summing sigmas, to average later
	    offspring_counts[i,j] = offspring_counts[i,j] + individual.tag;  // counting offspring for denominator
        }
    }
    return NULL;
}

1:999999999 late() {
    i2.evaluate(p1);
    print(c("Finished generation", sim.cycle, "; N=", p1.individualCount));
    
    // check if surviving
    if (p1.individualCount == 0){
        catn("extinct.");
        sim.simulationFinished();
    }
        
    // write output
    if (sim.cycle == maxgens) {
       // mean density over all gens
       De_means = De / asFloat(maxgens-gens_b4_record);

       // mean sigma over all dispersions
       for (i in seqLen(GRID_COARSENESS)){
       	   for (j in seqLen(GRID_COARSENESS)){
               if (offspring_counts[i,j] > 0){  // avoiding division by zero
               	  sigmas[i,j] = sqrt(sigmas[i,j] / offspring_counts[i,j]);
	       }
	   }
       }

       // write
       writeFile(paste0(OUTNAME, "_", SEED, "_tracked.txt"), paste(De_means, sep="\t"), append=F);
       writeFile(paste0(OUTNAME, "_", SEED, "_tracked.txt"), paste(sigmas, sep="\t"), append=T);
       sim.treeSeqOutput(paste(c(OUTNAME, "_", SEED,".trees"), sep=""));
       catn("Done.");
       sim.simulationFinished();
    }
}`

**Comment by ruizeliot** [comment]
Thank you for your quick answer. I used the benchmark.slim that I just slightly modified to changed the image width and the number of generations. What is the procedure to add mutations if needed as I am not familiar with slim and msprime?

[benchmark_custom.zip](https://github.com/user-attachments/files/17491786/benchmark_custom.zip)

**Comment by chriscrsmith** [comment]
We recommend a workflow where you do relatively few generations in slim (expensive) and then "finish" the simulation backwards in time with a coalescent model—called "recapitation"—and _then_ you can add mutations to the completed tree sequence. This workflow is described in general here: https://tskit.dev/pyslim/docs/latest/tutorial.html

The way I did this is using this function (mentioned briefly in the mapnn readme):
```
from process_input import recap
recap("tempout/sim_123.trees", "tempout/recap_123.trees", seed=123)
```

Did you use that `recap` function? I hope that addresses the problem, here.

**Comment by ruizeliot** [comment]
Hi again! Thanks for your answer!

I tried to run the recap function yesterday but it has been running since then while I have a small SNP dataset (loci number = 100), even though the geographic area is large (large part of the Western Indian Ocean). I checked in details and the function get stuck when running this row: self.Delta = self._create_incidence_matrix().

I also relaunched the SliM program with 50 generations (without the recap) but the preprocessing function of mapNN also fails:
`2024-10-24 14:05:32.251140: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-24 14:05:32.323373: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-24 14:05:33.434702: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
starting pre-processing pipeline
getting mean from training, on sim 0
getting sd from training, on sim 0

Traceback (most recent call last):
  File "/home/eruiz/mapNN/mapnn.py", line 1250, in <module>
    preprocess()
  File "/home/eruiz/mapNN/mapnn.py", line 938, in preprocess
    geno_mat, locs = training_generator.sample_ts(trees[i], args.seed) 
  File "/home/eruiz/mapNN/data_generation.py", line 334, in sample_ts
    new_genotypes = self.unpolarize(geno_mat0[shuffled_indices[s]])
IndexError: index 481 is out of bounds for axis 0 with size 481`

Thank for your help in advance!

**Comment by chriscrsmith** [comment]
On the one hand, it's normal for the slim step, and the recapitate to be slow, so the slow runtime by itself isn't necessarily a bug. But I'm confused about the detailed steps in your workflow. In particular you mentioned the SNP count in the file you are recapitating—that is different that the order I normally run things (slim -> recapitate -> add mutations).

You need to recapitate to complete the simulation before running the preprocess step with mapnn.

**Comment by ruizeliot** [comment]
Hi again! Here is the order I followed: vcf2genos (to get the .genos file) -> create_maps to get a training map -> cookie cutter on the training map -> slim -> preprocessing (this step is possibly preceded by the recap but too slow for me). I try to recapitate the SliM file...

**Comment by chriscrsmith** [comment]
Oops sorry I just noticed your comment about the line "self.Delta = self._create_incidence_matrix()". Will you please share (1) your recap() command, (2) the full error, and (3) and your tskit and msprime versions? 

Or is there no error and you're saying it continues running? Can you tell what package that line is in (e.g. maybe msprime)? It might be the case that your simulation just takes a super long time to run.

**Comment by Eliot-RUIZ** [comment]
Hi! I wasn't very clear in my previous message, but the problem with create_incidence_matrix concerns the function SpatialGraph that I was trying to use without the recap step. It outputs the error message I pasted in my previous message, which originates from create_incidence_matrix.

Concerning the recap function, there is no error message but it just get stuck running (I stopped it after 4 days). Here is the code to launch the recap function (I have tskit v0.5.5 and msprime v1.2.0): `recap("../ADLIFISH_eruiz/test1_mapNN_chr_t_top_100_snp/preprocessing_mapNN/sim_mapNN/chr_t_top_100_sim_123.trees", "../ADLIFISH_eruiz/test1_mapNN_chr_t_top_100_snp/preprocessing_mapNN/recap_mapNN/chr_t_top_100_recap_123.trees", seed=123)`. 

Meanwhile, I could get the result I wanted with EEMS in about one day using one CPU (achieving satisfying convergence) so I think computation time is not the problem...

**Comment by andrewkern** [comment]
seems very strange that a coalescent simulation would take > 4 days. how large is your chromosome? what is the associated recombination rate?
